#!/usr/bin/docker-compose -f

name: bookmarklet-generator
services:
  make:
    build: .
    entrypoint: "gmake"
    volumes:
      - .:/work
      - node_modules:/work/node_modules
volumes:
  node_modules:
